### ISSUE TITLE
Checklist - Release 1.0.0

### ISSUE THREAD

**Issue by scriptPilot** [scriptPilot/app-framework#13]
- [x] Complete all features
- [x] Demonstrate all features in demo app
- [x] Clean-up code of template files
- [x] Test with example application
- [x] Test on second computer according documentation
- [x] Update comments in code
- [x] Update documentation
- [x] Fix all bugs
- [x] Build
- [x] Release to hosting
- [x] Publish to npm
- [x] Remove WIP hints in readme and documentation
- [x] E-Mail templates okay for Firebase
- [x] Communicate
