### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by scriptPilot** [scriptPilot/app-framework#155]
Development
- [x] Complete all features
- [x] Fix all bugs
- [x] Adapt documentation

Testing
- [x] In web browser
- [x] In iOS simulator
- [x] Commit to GitHub
- [x] In existing test project with update from GitHub
- [x] In new test project with installation from GitHub

Deployment
- [x] Build version according milestone planning
- [x] Publish to npm
- [x] Deploy to Firebase hosting
- [x] Deploy to Apple App Store

Communication
- [x] Update milestone planning in readme file
- [x] Promote new version
