### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by scriptPilot** [scriptPilot/app-framework#187]
Development
- [x] Complete all features
- [x] Fix all bugs
- [x] Adapt documentation

Testing
- [x] In web browser
- [x] In iOS simulator
- [x] In Android simulator
- [x] In existing test project with local update
- [x] In new test project with local installation

Deployment
- [x] Build version according milestone planning
- [x] Publish to npm
- [x] Commit to GitHub
- [x] Deploy to Firebase hosting
- [x] Deploy to Apple App Store

Communication
- [x] Update milestone planning in readme file
- [x] Update external documentation
- [x] Promote new version
