### ISSUE TITLE
Release checklist for 1.4

### ISSUE THREAD

**Issue by scriptPilot** [scriptPilot/app-framework#341]
- [x] Create a branch "dev-x.y(.z)" for the next release
- [x] Open a project "Release x.y(.z)" with the following columns
  - Backlog
  - Development
  - Testing
  - Documentation
  - Done
- [x] Assign a bunch of issues to "Backlog"
- [x] Process all issues one by one
  - Development
    - Develop solution
    - Develop postinstall changes
    - Commit changes with issue closure reference
  - Testing
    - On macOS / Windows / Linux any script changes
    - On iOS / Android / Web any client code changes
    - With updated project any postinstall changes
    - Commit bug-fixes with issue reference
  - Documentation
    - Update documentation
    - Update readme file
    - Commit changes with issue reference
- [x] Build release according milestone planning
- [x] Publish to NPM
- [x] Commit to GitHub
- [x] Merge to master branch on GitHub
- [x] Deploy to Apple App Store (will be done for v1.5)
- [x] Deploy to Google Play Store (will be done for v1.5)
- [x] Deploy on Firebase hosting
- [x] Update roadmap in readme file
- [x] Update external documentation
- [x] Promote new version
- [x] Close project
